Remove Pragma header
helmetjs/nocache pull request #26
Opened 2023-05-31 18:19 UTC by dani2819

**What** 
This PR removes the support for `Pragma` header from the library

**Why**
The Pragma header was initially used to provide backward compatibility with HTTP/1.0 caches. However, with the widespread adoption of HTTP/1.1 and the introduction of cache-control directives, the Pragma header has become obsolete. The cache-control directives such as "no-cache" and "no-store" are now the standard mechanisms for controlling caching behaviour. It's also not recommend to use as it as a non-standard now as per MDN docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma

So, to align with the latest web standards and best practices, we are removing the Pragma header in this PR.

Related to:https://github.com/helmetjs/nocache/issues/25

2023-05-31 21:13 UTC, EvanHahn requested changes
Looks good other than two small things in the changelog. Thanks for doing this!

2023-05-31 21:13 UTC, EvanHahn commented on CHANGELOG.md
> +## 3.1.0 - 2023-05-31
Could you change this to `## Unreleased`??

```suggestion
## Unreleased
```

2023-05-31 21:13 UTC, EvanHahn commented on CHANGELOG.md
> +- Dropped support for Pragma header
Could you change this to:

```suggestion
- Breaking: dropped `Pragma` header. See [#26](https://github.com/helmetjs/nocache/pull/26)
```

2023-06-01 07:32 UTC, dani2819 commented on CHANGELOG.md
> +- Dropped support for Pragma header
Done!

2023-06-01 11:55 UTC, EvanHahn approved these changes
Looks great. Thank you!

2023-06-01 11:56 UTC, merged